"""
This type stub file was generated by pyright.
"""

PUBSUB_CHANNEL_TEMPLATE = ...
def send_command(connection, worker_name, command, **kwargs): # -> None:
    """Use connection' pubsub mechanism"""
    ...

def parse_payload(payload): # -> Any:
    """Returns a dict of command data"""
    ...

def send_shutdown_command(connection, worker_name): # -> None:
    """Send shutdown command"""
    ...

def send_kill_horse_command(connection, worker_name): # -> None:
    """Tell worker to kill it's horse"""
    ...

def send_stop_job_command(connection, job_id, serializer=...): # -> None:
    """Instruct a worker to stop a job"""
    ...

def handle_command(worker, payload): # -> None:
    """Parses payload and routes comman"""
    ...

def handle_shutdown_command(worker): # -> None:
    """Perform shutdown command"""
    ...

def handle_kill_worker_command(worker, payload): # -> None:
    """Stops work horse"""
    ...

def handle_stop_job_command(worker, payload): # -> None:
    """Handles stop job command"""
    ...

