"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager

class NoRedisConnectionException(Exception):
    ...


@contextmanager
def Connection(connection=...): # -> Generator[None, None, None]:
    ...

def push_connection(redis): # -> None:
    """Pushes the given connection on t"""
    ...

def pop_connection(): # -> Any | None:
    """Pops the topmost connection from"""
    ...

def use_connection(redis=...): # -> None:
    """Clears the stack and uses the gi"""
    ...

def get_current_connection(): # -> None:
    """Returns the current Redis connec"""
    ...

def resolve_connection(connection=...):
    """Convenience function to resolve """
    ...

_connection_stack = ...
__all__ = ['Connection', 'get_current_connection', 'push_connection', 'pop_connection', 'use_connection']
