"""
This type stub file was generated by pyright.
"""

class job:
    queue_class = ...
    def __init__(self, queue, connection=..., timeout=..., result_ttl=..., ttl=..., queue_class=..., depends_on=..., at_front=..., meta=..., description=..., failure_ttl=..., retry=...) -> None:
        """A decorator that adds a ``delay`"""
        ...
    
    def __call__(self, f):
        ...
    


