"""
This type stub file was generated by pyright.
"""

"""
Some dummy tasks that are well-"""
def do_nothing(): # -> None:
    ...

def sleep(secs): # -> None:
    ...

def endless_loop():
    ...

def div_by_zero(): # -> None:
    ...

def fib(n): # -> Literal[1]:
    ...

def random_failure(): # -> Literal['OK']:
    ...

