"""
This type stub file was generated by pyright.
"""

class NoSuchJobError(Exception):
    ...


class DeserializationError(Exception):
    ...


class InvalidJobDependency(Exception):
    ...


class InvalidJobOperationError(Exception):
    ...


class InvalidJobOperation(Exception):
    ...


class DequeueTimeout(Exception):
    ...


class ShutDownImminentException(Exception):
    def __init__(self, msg, extra_info) -> None:
        ...
    


class TimeoutFormatError(Exception):
    ...


