"""
This type stub file was generated by pyright.
"""

class DefaultSerializer:
    dumps = ...
    loads = ...


class JSONSerializer:
    @staticmethod
    def dumps(*args, **kwargs): # -> bytes:
        ...
    
    @staticmethod
    def loads(s, *args, **kwargs): # -> Any:
        ...
    


def resolve_serializer(serializer): # -> Type[DefaultSerializer] | Any:
    """This function checks the user de"""
    ...

