"""
This type stub file was generated by pyright.
"""

WORKERS_SUSPENDED = ...
def is_suspended(connection, worker=...):
    ...

def suspend(connection, ttl=...): # -> None:
    """ttl = time to live in seconds.  """
    ...

def resume(connection):
    ...

