"""
This type stub file was generated by pyright.
"""

class BaseTimeoutException(Exception):
    """Base exception for timeouts."""
    ...


class JobTimeoutException(BaseTimeoutException):
    """Raised when a job takes longer t"""
    ...


class HorseMonitorTimeoutException(BaseTimeoutException):
    """Raised when waiting for a horse """
    ...


class BaseDeathPenalty:
    """Base class to setup job timeouts"""
    def __init__(self, timeout, exception=..., **kwargs) -> None:
        ...
    
    def __enter__(self): # -> None:
        ...
    
    def __exit__(self, type, value, traceback): # -> Literal[False]:
        ...
    
    def setup_death_penalty(self):
        ...
    
    def cancel_death_penalty(self):
        ...
    


class UnixSignalDeathPenalty(BaseDeathPenalty):
    def handle_death_penalty(self, signum, frame):
        ...
    
    def setup_death_penalty(self): # -> None:
        """Sets up an alarm signal and a si"""
        ...
    
    def cancel_death_penalty(self): # -> None:
        """Removes the death penalty alarm """
        ...
    


