"""
This type stub file was generated by pyright.
"""

import sys
from __future__ import absolute_import, division, print_function, unicode_literals

def is_python_version(*versions): # -> bool:
    ...

PY2 = ...
text_type = str
string_types = ...
def as_text(v): # -> str | None:
    ...

def decode_redis_hash(h): # -> dict[str | None, Unknown]:
    ...

